### ISSUE TITLE
Morning Session Code Review

### ISSUE THREAD

**Issue by AbuRayhaan** [mandelatuks/To-do-list-webApps#7]
Hello @mandelatuks, you have done a great job so far 🥇 .

![](https://media.giphy.com/media/cEODGfeOYMRxK/giphy.gif) 

## **To Highlight: ⚪**
✅  There are no linters error.
✅  No DRY, KISS, and YAGNI found.
✅  Clean code.

## **To improve: 🔴** 
- Kindly fix the deletion feature for the last task-item in the list.
- Kindly update the LICENSE to reflect your name and year.

**Comment by mandelatuks** [comment]
@AbuRayhaan  
- thanks for your review and changes have been done 
 cheers and happy coding 👍
